export type PostWritingStyle =
    | "formal"
    | "informal"
    | "professional"
    | "casual"
    | "technical"
    | "creative"
    | "persuasive"
    | "conversational"
    | "storytelling"
    | "knowledgeable"
    | "humorous"
    | "analytical"
    | "inspirational"
    | "educational"
    | "reflective"
    | "persuasive"
    | "minimalist";
